// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "d8c00c24c4e277b2f88d5107ea934201"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"dd1ee035574cfa7beaeca289d9042b01": "1f8b08000000000000ff5cce4daac24010c4f17d9fa296efa13941b65ec1b5749226699c2f7b7a88737b5141c45dc1bf16bf61c021ea6aec8273219a4d9ed3790a029ee7dc9257fc1100e88249d72aa61c504c235bc755faf15525b206b8dc1d293b520b012de9adc9bb17ae75cfb65c36ae1ba6eec29f23fd8f44df9453de13d162b9fc50467a040000ffff3c13a404b2000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("01_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "dd1ee035574cfa7beaeca289d9042b01"})
	}()
	return nil
}()
