// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "d8c00c24c4e277b2f88d5107ea934201"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"dd1ee035574cfa7beaeca289d9042b01": "1f8b08000000000000ff5ccebdaac24010c5f17e9ee29409f7a611acd2fa0a3ec06433c4c1fd7276d7b06f2f2a88d81d38ffe2374df80bba1957c139133993e7acbc78013b975aac05030180ae58742b62ca1ed934b0755ca5ffbf5e09ac1e773677611b0ec7113155c4e63d5ad45b937796b9943dd98aa557e14f43e34cf48d39a53d12ad96f20f66a647000000ffffe4c4252bb4000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("01_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "dd1ee035574cfa7beaeca289d9042b01"})
	}()
	return nil
}()
